#!/usr/bin/env ruby
#
# Copyright (C) 2026 The Waydroid-ATV project
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see https://www.gnu.org/licenses/gpl-3.0.html.
#

bins_32bit  = Dir['prebuilts/bin/arm/*'].map { |lib| File.basename(lib) }
bins_64bit  = Dir['prebuilts/bin/arm64/*'].map { |lib| File.basename(lib) }
libs_32bit  = Dir['prebuilts/lib/**/*.so'].map { |lib| File.basename(lib, '.so') }
libs_64bit  = Dir['prebuilts/lib64/**/*.so'].map { |lib| File.basename(lib, '.so') }
libs_common = libs_32bit & libs_64bit
android_bp  = File.open('Android.bp', 'w')

android_bp.write "// Auto-generated by generate-blueprint.rb, DO NOT MODIFY!\n\n"

[32, 64].each do |arch|
    arch_name = arch == 64 ? 'arm64' : 'arm'
    libdir    = arch == 64 ? 'lib64' : 'lib'

    eval("bins_#{arch}bit").each do |bin|
        android_bp.write <<~EOF + "\n"
            cc_prebuilt_binary {
                name: "ndk_translation-#{bin}",
                stem: "#{bin}",
                check_elf_files: false,
                compile_multilib: "#{arch}",
                relative_install_path: "#{arch_name}",
                srcs: ["prebuilts/bin/#{arch_name}/#{bin}"],
                strip: {
                    none: true,
                },
            }
        EOF
    end

    eval("libs_#{arch}bit - libs_common").each do |lib|
        lib_path = Dir["prebuilts/#{libdir}/**/#{lib}.so"][0].sub(%r{^prebuilts/#{libdir}/}, '')

        android_bp.write <<~EOF + "\n"
            cc_prebuilt_library_shared {
                name: "ndk_translation-#{lib}",
                stem: "#{lib}",
                check_elf_files: false,
                compile_multilib: "#{arch}",
                relative_install_path: "#{File.dirname(lib_path)}",
                srcs: ["prebuilts/#{libdir}/#{lib_path}"],
                strip: {
                    none: true,
                },
            }
        EOF
    end
end

libs_common.each do |lib|
    lib_path = Dir["prebuilts/{lib,lib64}/**/#{lib}.so"][0].sub(%r{^prebuilts/lib(64)?/}, '')
    arm_lib  = lib_path.start_with?('arm')

    android_bp.write <<~EOF + "\n"
        cc_prebuilt_library_shared {
            name: "ndk_translation-#{lib}",
            stem: "#{lib}",
            check_elf_files: false,
            compile_multilib: "both",
            arch: {
                x86: {
                    relative_install_path: "#{arm_lib ? 'arm' : '.'}",
                    srcs: ["prebuilts/lib/#{arm_lib ? "arm/#{lib}.so" : "#{lib}.so"}"],
                },
                x86_64: {
                    relative_install_path: "#{arm_lib ? 'arm64' : '.'}",
                    srcs: ["prebuilts/lib64/#{arm_lib ? "arm64/#{lib}.so" : "#{lib}.so"}"],
                },
            },
            strip: {
                none: true
            }
        }
    EOF
end

android_bp.write <<~EOF
    prebuilt_etc {
        name: "ndk_translation-cpuinfo",
        srcs: ["prebuilts/etc/cpuinfo.arm.txt"],
    }

    prebuilt_etc {
        name: "ndk_translation-cpuinfo64",
        srcs: ["prebuilts/etc/cpuinfo.arm64.txt"],
    }

    prebuilt_etc {
        name: "ndk_translation-ldconfig",
        srcs: ["prebuilts/etc/ld.config.arm.txt"],
    }

    prebuilt_etc {
        name: "ndk_translation-ldconfig64",
        srcs: ["prebuilts/etc/ld.config.arm64.txt"],
    }

    cc_prebuilt_binary {
        name: "ndk_translation_program_runner",
        check_elf_files: false,
        compile_multilib: "both",
        enabled: false,
        arch: {
            x86: {
                enabled: true,
                stem: "ndk_translation_program_runner_binfmt_misc",
                srcs: ["prebuilts/bin/ndk_translation_program_runner_binfmt_misc"],
                required: ["libberberis_exec_region", "ndk_translation-cpuinfo", "ndk_translation-ldconfig", #{(bins_32bit + libs_32bit).map { |f| "ndk_translation-#{f}".inspect } .join(', ')}],
            },
            x86_64: {
                enabled: true,
                stem: "ndk_translation_program_runner_binfmt_misc_arm64",
                srcs: ["prebuilts/bin/ndk_translation_program_runner_binfmt_misc_arm64"],
                required: ["libberberis_exec_region", "ndk_translation-cpuinfo64", "ndk_translation-ldconfig64", #{(bins_64bit + libs_64bit).map { |f| "ndk_translation-#{f}".inspect } .join(', ')}],
            },
        },
        init_rc: ["prebuilts/etc/init/ndk_translation.rc"],
        strip: {
            none: true,
        },
    }
EOF
